# Change these first
owner: jacklebeignet # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Beignet API
    url: https://beignet-api.wisp.uno/status
  - name: Beignet API (backup)
    url: http://beignet.deez.nz:15037/status

assignees:
  - jacklebeignet

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Official page for monitoring my scripts."
  introMessage: "Welcome, everyone!"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

secrets:
  - NOTIFICATION_DISCORD_WEBHOOK_URL

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
